Repository iqiyi/dpvs, pull requests merged in 2020-09, with the labels that each got.

#649 ipvsadm: fix change conhash target error
  tools/keepalived/keepalived/check/libipvs.c
Labels: pr/accepted, pr/bug-confirmed

#652 ipvsadm: fix ipvsadm -ln show null error
  tools/keepalived/keepalived/include/check_data.h
  tools/keepalived/keepalived/include/ip_vs.h
Labels: pr/accepted, pr/codes-reviewed-ok

#651 Bugfix
  src/netif.c
  tools/ipvsadm/ipvsadm.c
Labels: pr/accepted

#654 sockopts: replace tc_oper_t with sockoptid_t.
  include/conf/common.h
  include/conf/laddr.h
  include/conf/sockopts.h
  include/ctrl.h
  src/tc/tc_ctrl.c
Labels: pr/accepted, pr/codes-reviewed-ok

#614 dpvs support mh scheduling algorithm
  include/ipvs/kcompat.h
  include/ipvs/mh.h
  include/ipvs/sched.h
  include/ipvs/service.h
  include/ipvs/siphash.h
  src/ipvs/ip_vs_conhash.c
  src/ipvs/ip_vs_core.c
  src/ipvs/ip_vs_fo.c
  src/ipvs/ip_vs_mh.c
  src/ipvs/ip_vs_rr.c
  src/ipvs/ip_vs_sched.c
  src/ipvs/ip_vs_wlc.c
  src/ipvs/ip_vs_wrr.c
  src/ipvs/kcompat.c
  src/ipvs/siphash.c
  tools/keepalived/keepalived/check/check_parser.c
Labels: pr/accepted, pr/codes-reviewed-ok, pr/needs-confirmed
