Repository iqiyi/dpvs, pull requests merged in 2020-07, with the labels that each got.

#500 Timer wild callback
  conf/dpvs.conf.items
  conf/dpvs.conf.sample
  conf/dpvs.conf.single-bond.sample
  conf/dpvs.conf.single-nic.sample
  include/timer.h
  src/neigh.c
  src/timer.c
Labels: pr/accepted, pr/codes-reviewed-ok

#548 test: add test cases for dpvs release
  test/release/checklist.md
  test/release/v1.7.2/checklist-v1.7.2.md
  test/release/v1.7.2/checklist_setup.sh
Labels: pr/accepted, pr/codes-reviewed-ok

#571 kmod/toa: support 4.18.x kernels
  kmod/toa/toa.c
  kmod/toa/toa.h
Labels: duplicate, pr/accepted, pr/codes-reviewed-ok, pr/codes-tested-ok, pr/compatibility-ok

#596 scheduler: a performance optimization
  src/scheduler.c
Labels: pr/accepted

#597 remove some useless code
  src/global_data.c
  src/log.c
  src/netif.c
Labels: pr/accepted, pr/codes-reviewed-ok, pr/codes-tested-ok

#501 fdir: add "filter" switch of fdir config to support multi-core processing in VM
  conf/dpvs.conf.items
  include/netif.h
  src/netif.c
  src/sa_pool.c
Labels: pr/accepted, pr/codes-reviewed-ok, pr/codes-tested-ok, pr/needs-confirmed

#592 dpip: show dpdk mem info
  include/conf/eal_mem.h
  include/eal_mem.h
  src/eal_mem.c
  src/main.c
  tools/dpip/Makefile
  tools/dpip/dpip.c
  tools/dpip/eal_mem.c
Labels: pr/accepted, pr/codes-reviewed-ok, pr/codes-tested-ok, pr/needs-confirmed

#593 conhash: use weight ratio to reduce virtual node num in rbtree
  include/ipvs/sched.h
  src/ipvs/ip_vs_conhash.c
  src/ipvs/ip_vs_sched.c
  src/ipvs/ip_vs_wrr.c
Labels: pr/accepted, pr/bug-confirmed, pr/codes-reviewed-ok, pr/codes-tested-ok

#607 conf: move the types of portid_t and queueid_t to conf/common.h.
  include/conf/common.h
  include/conf/netif.h
  include/dpdk.h
Labels: pr/accepted, pr/codes-reviewed-ok

#609 Fix mod ifa bug.
  src/inetaddr.c
Labels: pr/accepted, pr/codes-reviewed-ok
