Repository iqiyi/dpvs, pull requests merged in 2020-08, with the labels that each got.

#599 Correct ret value of netlink_route
  tools/keepalived/keepalived/vrrp/vrrp_iproute.c
Labels: pr/accepted, pr/codes-reviewed-ok, pr/codes-tested-ok, pr/needs-confirmed

#606 fix per lcore need mcast init
  include/inetaddr.h
  src/inetaddr.c
  src/netif.c
Labels: pr/accepted, pr/bug-confirmed

#618 icmp: add the debugging info of src_ip and dst_ip for bad checksum pa…
  src/icmp.c
Labels: pr/accepted, pr/codes-reviewed-ok, pr/needs-confirmed

#620 keepalived patch for compiling error on Ubuntu
  patch/ubuntu_keepalived.patch
Labels: pr/accepted, pr/codes-reviewed-ok

#512 pdump filter by five tuple.
  patch/dpdk-stable-17.11.2/0003-pdump-support-filter.patch
Labels: duplicate, pr/accepted, pr/codes-reviewed-ok, pr/codes-tested-ok, pr/needs-confirmed

#610 Reuse expired ifa during adding ifa.
  include/sa_pool.h
  src/inetaddr.c
  src/sa_pool.c
Labels: pr/accepted, pr/bug-confirmed, pr/codes-reviewed-ok, pr/codes-tested-ok

#625 Add support for ENA driver on AWS
  src/dpdk.mk
Labels: pr/accepted

#629 fix the compiling error with dpdk 18.11
  patch/dpdk-stable-18.11.2/0004-rm-rte_experimental-attribute-of-rte_memseg_walk.patch
  src/eal_mem.c
Labels: pr/accepted, pr/codes-reviewed-ok, pr/codes-tested-ok

#600 add dpdk-pdump filter by five tuple for dpvs.
  patch/dpdk-stable-18.11.2/0004-enable-pdump-and-change-dpdk-pdump-tool-for-dpvs.patch
  src/config.mk
  src/dpdk.mk
Labels: pr/accepted, pr/codes-need-change, pr/needs-confirmed

#632 fix compile problem for pdump of dpdk-18.11.2
  conf/dpvs.bond.conf.sample
  conf/dpvs.conf.items
  conf/dpvs.conf.sample
  patch/dpdk-stable-17.11.2/0003-enable-pdump-and-change-dpdk-pdump-tool-for-DPVS.patch
  patch/dpdk-stable-18.11.2/0005-enable-pdump-and-change-dpdk-pdump-tool-for-dpvs.patch
  src/config.mk
  src/dpdk.mk
  src/global_conf.c
  src/main.c
Labels: pr/codes-tested-ok

#617 One Packet Scheduler for UDP
  include/ipvs/conn.h
  include/ipvs/service.h
  src/ipvs/ip_vs_conn.c
  src/ipvs/ip_vs_core.c
  tools/ipvsadm/ipvsadm.c
Labels: pr/accepted, pr/codes-reviewed-ok, pr/codes-tested-ok, pr/needs-confirmed

#623 sockopts: Centralize all the SOCKOPT_SET/GET_XXX definitions into one…
  include/conf/blklst.h
  include/conf/conn.h
  include/conf/iftraf.h
  include/conf/inetaddr.h
  include/conf/ip_tunnel.h
  include/conf/ipset.h
  include/conf/ipv6.h
  include/conf/laddr.h
  include/conf/neigh.h
  include/conf/netif.h
  include/conf/route.h
  include/conf/route6.h
  include/conf/service.h
  include/conf/sockopts.h
  include/conf/tc.h
  include/conf/vlan.h
  src/ipvs/ip_vs_conn.c
Labels: pr/accepted, pr/codes-tested-ok, pr/needs-confirmed

#635 Optimized sa_entry memory.
  include/sa_pool.h
  src/sa_pool.c
Labels: pr/accepted, pr/codes-reviewed-ok, pr/codes-tested-ok, pr/needs-confirmed

#643 keepalived: fix keepalived compile error with kernel 3.11 and above
  tools/keepalived/keepalived/include/keepalived_netlink.h
Labels: pr/accepted
