Repository iqiyi/dpvs, pull requests merged in 2020-11, with the labels that each got.

#660 fix the dest max conn bug
  src/ipvs/ip_vs_dest.c
  src/ipvs/ip_vs_service.c
  tools/keepalived/keepalived/check/ipwrapper.c
  tools/keepalived/keepalived/include/check_data.h
Labels: pr/accepted, pr/bug-confirmed, pr/codes-reviewed-ok, pr/codes-tested-ok

#662 kmod/toa: fix is_ro_addr()
  kmod/toa/toa.c
Labels: pr/accepted, pr/codes-reviewed-ok, pr/codes-tested-ok

#666 Sometimes RS can't get client ip
  src/ipvs/ip_vs_proto_tcp.c
Labels: pr/accepted, pr/bug-confirmed, pr/codes-reviewed-ok, pr/codes-tested-ok

#667 Use the same RTE_MACHINE and CPU CFLAGS as DPDK
  src/Makefile
  src/dpdk.mk
  src/main.c
Labels: pr/accepted, pr/bug-confirmed, pr/codes-reviewed-ok, pr/codes-tested-ok

#672 KNI Worker Isolation (based on PR #601)
  conf/dpvs.bond.conf.sample
  conf/dpvs.conf.items
  conf/dpvs.conf.sample
  conf/dpvs.conf.single-bond.sample
  conf/dpvs.conf.single-nic.sample
  include/conf/netif.h
  include/global_data.h
  include/netif.h
  src/ipset.c
  src/ipvs/ip_vs_conn.c
  src/ipvs/ip_vs_redirect.c
  src/ipvs/ip_vs_synproxy.c
  src/ipvs/ip_vs_xmit.c
  src/kni.c
  src/neigh.c
  src/netif.c
  src/scheduler.c
  src/tc/sch_generic.c
  src/vlan.c
  tools/dpip/link.c
Labels: pr/accepted, pr/codes-reviewed-ok

#674 main.c: code refactoring on the initialization/termination of all the…
  include/netif.h
  src/main.c
  src/netif.c
Labels: pr/accepted, pr/codes-tested-ok, pr/needs-confirmed

#675 job: simplify the initialization of all types of the jobs.
  include/scheduler.h
  src/cfgfile.c
  src/ctrl.c
  src/iftraf.c
  src/ipv4_frag.c
  src/neigh.c
  src/netif.c
  src/scheduler.c
Labels: pr/accepted, pr/codes-tested-ok, pr/needs-confirmed

#680 Delete functions that are not in use.
  include/netif.h
  src/netif.c
Labels: pr/accepted, pr/codes-reviewed-ok

#685 set SO_LINGER to 0 in case of TIME_WAIT
  tools/keepalived/keepalived/core/layer4.c
Labels: pr/codes-reviewed-ok

#683 fix:1.disable hash targent; 2.always print log info:hash target not s…
  tools/keepalived/keepalived/check/check_data.c
Labels: pr/accepted, pr/codes-reviewed-ok

#684 Add port and proto match when deleting blacklist.
  src/ipvs/ip_vs_blklst.c
Labels: pr/accepted, pr/bug-confirmed, pr/codes-reviewed-ok
