Repository iqiyi/dpvs, pull requests merged in 2021-01, with the labels that each got.

#657 show dpvs's ip in traceroute path
  src/ipv4.c
Labels: pr/accepted, pr/codes-reviewed-ok

#691 added white list
  README.md
  include/conf/conn.h
  include/conf/sockopts.h
  include/conf/whtlst.h
  include/ctrl.h
  include/ipvs/whtlst.h
  src/ipvs/ip_vs_blklst.c
  src/ipvs/ip_vs_core.c
  src/ipvs/ip_vs_proto_tcp.c
  src/ipvs/ip_vs_proto_udp.c
  src/ipvs/ip_vs_service.c
  src/ipvs/ip_vs_synproxy.c
  src/ipvs/ip_vs_whtlst.c
  tools/ipvsadm/ipvsadm.c
  tools/keepalived/keepalived/check/check_data.c
  tools/keepalived/keepalived/check/check_parser.c
  tools/keepalived/keepalived/check/ipvswrapper.c
  tools/keepalived/keepalived/check/ipwrapper.c
  tools/keepalived/keepalived/check/libipvs.c
  tools/keepalived/keepalived/include/check_data.h
  tools/keepalived/keepalived/include/dp_vs.h
  tools/keepalived/keepalived/include/ip_vs.h
  tools/keepalived/keepalived/include/ipvswrapper.h
  tools/keepalived/keepalived/include/ipwrapper.h
  tools/keepalived/keepalived/include/libipvs.h
Labels: pr/accepted, pr/codes-reviewed-ok, pr/codes-tested-ok, pr/needs-confirmed

#697 fix: UDP checksum not correct using ipo UOA with checksum offloading disabled
  include/ipv4.h
Labels: pr/accepted, pr/codes-reviewed-ok, pr/codes-tested-ok
