Repository iqiyi/dpvs, pull requests merged in 2021-11, with the labels that each got.

#765 Update ip_vs_laddr.c
  src/ipvs/ip_vs_laddr.c
Labels: pr/accepted

#766 correct README.md guide for dpvs 1.9.0 build failed by exporting erro…
  README.md
Labels: pr/accepted

#761 fix: wrong checksum if inbound and outbound offload flags are different
  src/ipvs/ip_vs_proto_tcp.c
  src/ipvs/ip_vs_proto_udp.c
Labels: pr/codes-reviewed-ok, pr/codes-tested-ok, pr/accepted

#762 keepalived: bugfix
  tools/keepalived/keepalived/check/ipvswrapper.c
  tools/keepalived/keepalived/check/ipwrapper.c
Labels: pr/codes-tested-ok, pr/accepted

#769 toa : support kernel version 5.7.0
  kmod/toa/toa.c
  kmod/toa/toa.h
Labels: pr/codes-reviewed-ok, pr/codes-tested-ok, pr/accepted

#768 Ipset Update
  doc/IPset.md
  include/conf/ipset.h
  include/conf/sockopts.h
  include/ipset/ipset.h
  include/ipset/ipset_bitmap.h
  include/ipset/ipset_hash.h
  src/ipset/ipset_bitmap.c
  src/ipset/ipset_bitmap_ip.c
  src/ipset/ipset_bitmap_ipmac.c
  src/ipset/ipset_bitmap_port.c
  src/ipset/ipset_core.c
  src/ipset/ipset_ctrl.c
  src/ipset/ipset_hash.c
  src/ipset/ipset_hash_ip.c
  src/ipset/ipset_hash_ipport.c
  src/ipset/ipset_hash_ipportip.c
  src/ipset/ipset_hash_ipportnet.c
  src/ipset/ipset_hash_net.c
  src/ipset/ipset_hash_netport.c
  src/ipset/ipset_hash_netportiface.c
  src/ipset/ipset_hash_netportnet.c
  src/ipset/ipset_hash_netportnetport.c
  test/ipset/dpip.log
  test/ipset/dpip.sh
  tools/dpip/Makefile
  tools/dpip/dpip.c
  tools/dpip/dpip.h
  tools/dpip/iftraf.c
  tools/dpip/ipset.c
Labels: pr/accepted
