Repository iqiyi/dpvs, pull requests merged in 2021-08, with the labels that each got.

#748 fix dpvs_sockopts sockoptid_t register duplicated in sockopts_exist
  src/ctrl.c
Labels: pr/codes-reviewed-ok

#750 Bonding bugfix
  conf/dpvs.bond.conf.sample
  conf/dpvs.conf.items
  conf/dpvs.conf.sample
  conf/dpvs.conf.single-bond.sample
  conf/dpvs.conf.single-nic.sample
  include/conf/common.h
  include/conf/neigh.h
  include/netif.h
  patch/dpdk-stable-20.11.1/0001-kni-use-netlink-event-for-multicast-driver-part.patch
  patch/dpdk-stable-20.11.1/0002-pdump-change-dpdk-pdump-tool-for-dpvs.patch
  patch/dpdk-stable-20.11.1/0003-for-debug-only-enable-dpdk-eal-memory-debug.patch
  patch/dpdk-stable-20.11.1/0004-ixgbe_flow-patch-ixgbe-fdir-rte_flow-for-dpvs.patch
  patch/dpdk-stable-20.11.1/0005-Fix-bonding-mode-4-problem.patch
  patch/dpdk-stable-20.11.1/0006-bonding-allow-slaves-from-different-numa-nodes.patch
  src/common.c
  src/ctrl.c
  src/ipv6/ipv6.c
  src/kni.c
  src/netif.c
Labels: pr/bug-confirmed, pr/accepted

#747 Release v1.9.0
  README.md
  src/Makefile
  src/VERSION
Labels: pr/accepted
