Repository iqiyi/dpvs, pull requests merged in 2022-01, with the labels that each got.

#778 conn: reduce memory usage of dp_vs_conn
  include/ipvs/conn.h
Labels: pr/codes-reviewed-ok, pr/accepted

#779 bugfix: unreasonable conhash weight ratio while updating rs
  src/ipvs/ip_vs_conhash.c
Labels: pr/codes-reviewed-ok, pr/codes-tested-ok, pr/accepted

#782 bugfix: dpdk-pdump can't use 'device_id=net_bondingX'
  src/netif.c
Labels: pr/codes-tested-ok, pr/accepted

#786 modify bug: icmp6 checksum error
  src/ipv6/icmp6.c
Labels: pr/codes-reviewed-ok, pr/accepted

#794 kni rx isolation using rte_flow
  conf/dpvs.bond.conf.sample
  conf/dpvs.conf.items
  conf/dpvs.conf.sample
  conf/dpvs.conf.single-bond.sample
  conf/dpvs.conf.single-nic.sample
  doc/Worker-Performance-Tuning.md
  doc/pics/kni-flow-1.png
  doc/pics/kni-flow-2.png
  doc/pics/kni-flow.drawio
  include/conf/kni.h
  include/conf/sockopts.h
  include/kni.h
  include/netif.h
  include/netif_flow.h
  src/config.mk
  src/kni.c
  src/main.c
  src/netif.c
  src/netif_flow.c
  test/flameGraph/README.md
  test/flameGraph/flamegraph.pl
  test/flameGraph/run.sh
  test/flameGraph/stackcollapse-perf.pl
  tools/dpip/Makefile
  tools/dpip/dpip.c
  tools/dpip/flow.c
Labels: pr/codes-reviewed-ok, pr/accepted

#793 modify bug: icmp6 mtu error, tunnel mode icmp/icmp6 error
  src/ipvs/ip_vs_core.c
  src/ipvs/ip_vs_xmit.c
Labels: pr/codes-reviewed-ok, pr/accepted

#792 modify bug: SNAT mode, ipvsadm displaying and editing the SVC will fail.
  tools/ipvsadm/ipvsadm.c
  tools/keepalived/keepalived/check/libipvs.c
Labels: pr/bug-confirmed, pr/accepted
