Repository iqiyi/dpvs, pull requests merged in 2024-04, with the labels that each got.

#937 Fix backend update racing problem with dpvs-agent and healthcheck.
  src/VERSION
  src/ipvs/ip_vs_dest.c
  tools/dpvs-agent/cmd/dpvs-agent-server/local_init.go
  tools/dpvs-agent/cmd/ipvs/delete_vs_vip_port.go
  tools/dpvs-agent/cmd/ipvs/get_vs.go
  tools/dpvs-agent/cmd/ipvs/get_vs_vip_port.go
  tools/dpvs-agent/cmd/ipvs/post_vs_vip_port_rs.go
  tools/dpvs-agent/cmd/ipvs/put_vs_vip_port.go
  tools/dpvs-agent/cmd/ipvs/put_vs_vip_port_rs.go
  tools/dpvs-agent/cmd/ipvs/put_vs_vip_port_rs_health.go
  tools/dpvs-agent/dpvs-agent-api.yaml
  tools/dpvs-agent/models/dest_check_spec.go
  tools/dpvs-agent/pkg/ipc/types/snapshot.go
  tools/dpvs-agent/pkg/settings/settings.go
  tools/dpvs-agent/restapi/embedded_spec.go
  tools/dpvs-agent/restapi/operations/virtualserver/get_vs_parameters.go
  tools/dpvs-agent/restapi/operations/virtualserver/get_vs_responses.go
  tools/dpvs-agent/restapi/operations/virtualserver/get_vs_urlbuilder.go
  tools/dpvs-agent/restapi/operations/virtualserver/get_vs_vip_port_parameters.go
  tools/dpvs-agent/restapi/operations/virtualserver/get_vs_vip_port_urlbuilder.go
  tools/dpvs-agent/restapi/operations/virtualserver/put_vs_vip_port_rs_health_responses.go
  tools/healthcheck/pkg/helthcheck/checker.go
  tools/healthcheck/pkg/helthcheck/configs.go
  tools/healthcheck/pkg/helthcheck/http_checker.go
  tools/healthcheck/pkg/helthcheck/http_checker_test.go
  tools/healthcheck/pkg/helthcheck/ping_checker.go
  tools/healthcheck/pkg/helthcheck/ping_checker_test.go
  tools/healthcheck/pkg/helthcheck/server.go
  tools/healthcheck/pkg/helthcheck/types.go
  tools/healthcheck/pkg/helthcheck/udp_ping_checker_test.go
  tools/healthcheck/pkg/lb/dpvs_agent.go
  tools/healthcheck/pkg/lb/dpvs_agent_test.go
  tools/healthcheck/pkg/lb/types.go
  tools/healthcheck/test/stress-test.sh
Labels: pr/accepted

#938 use better random source
  src/ipvs/ip_vs_synproxy.c
Labels: pr/codes-reviewed-ok, pr/accepted

#945 bugfix: new_vs quorum_up script will not be excuted
  tools/keepalived/keepalived/check/ipwrapper.c
Labels: pr/bug-confirmed, pr/accepted

#954 ip_vs_conn: A small improvement
  src/ipvs/ip_vs_conn.c
Labels: pr/codes-reviewed-ok
