Repository iqiyi/dpvs, pull requests merged in 2024-09, with the labels that each got.

#993 define buffer size by INET6_ADDRSTRLEN
  src/ipvs/ip_vs_proxy_proto.c
Labels: pr/codes-reviewed-ok

#995 Bugfix 20240902
  conf/dpvs.conf.items
  include/conf/inetaddr.h
  include/ctrl.h
  include/inetaddr.h
  include/ip_tunnel.h
  include/ipv6.h
  include/linux_ipv6.h
  include/netif.h
  src/inetaddr.c
  src/ip_gre.c
  src/ip_tunnel.c
  src/ipip.c
  src/ipset/ipset_core.c
  src/ipv6/ipv6.c
  src/ipv6/route6.c
  src/ipvs/ip_vs_blklst.c
  src/ipvs/ip_vs_conn.c
  src/ipvs/ip_vs_whtlst.c
  src/netif.c
  src/route.c
  src/scheduler.c
  src/timer.c
  src/vlan.c
Labels: pr/codes-reviewed-ok, pr/codes-tested-ok, pr/accepted

#996 V1.9.8
  README.md
  include/sctp/sctp.h
  patch/dpdk-stable-20.11.10/0001-kni-use-netlink-event-for-multicast-driver-part.patch
  patch/dpdk-stable-20.11.10/0002-pdump-change-dpdk-pdump-tool-for-dpvs.patch
  patch/dpdk-stable-20.11.10/0003-debug-enable-dpdk-eal-memory-debug.patch
  patch/dpdk-stable-20.11.10/0004-ixgbe_flow-patch-ixgbe-fdir-rte_flow-for-dpvs.patch
  patch/dpdk-stable-20.11.10/0005-bonding-allow-slaves-from-different-numa-nodes.patch
  patch/dpdk-stable-20.11.10/0006-bonding-fix-problem-in-mode-4-dropping-multicast-pac.patch
  patch/dpdk-stable-20.11.10/0007-bonding-device-sends-packets-with-user-specified-sal.patch
  pic/dpvs.drawio
  pic/dpvs.png
  pic/dpvs.svg
  pic/modules.png
  pic/modules.svg
  scripts/dpdk-build.sh
  src/VERSION
  src/dpdk.mk
  src/inetaddr.c
  tools/dpvs-agent/cmd/dpvs-agent-server/Makefile
  tools/healthcheck/Makefile
  tools/ipvsadm/ipvsadm.c
  tools/keepalived/keepalived/include/layer4.h
  tools/keepalived/keepalived/vrrp/vrrp_daemon.c
Labels: pr/codes-reviewed-ok, pr/accepted

#997 Bugfix 20240919
  scripts/dpdk-build.sh
  src/VERSION
  src/netif.c
Labels: pr/accepted
