Repository iqiyi/dpvs, pull requests merged in 2024-07, with the labels that each got.

#980 ci: fix unsupported Node20 problem
  .github/workflows/build.yaml
  .github/workflows/run.yaml
Labels: pr/codes-tested-ok

#972 fix compile error on RHEL 9.4
  kmod/uoa/uoa.c
Labels: pr/codes-reviewed-ok, pr/accepted

#977 README: add ipvsadm RS port
  README.md
Labels: pr/accepted
